BEGIN;

CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    CONSTRAINT password_reset_tokens_token_hash_unique UNIQUE (token_hash),
    CONSTRAINT password_reset_tokens_expires_after_created CHECK (expires_at > created_at),
    CONSTRAINT password_reset_tokens_used_after_created CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX IF NOT EXISTS password_reset_tokens_user_id_idx
    ON public.password_reset_tokens (user_id);

CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_at_idx
    ON public.password_reset_tokens (expires_at);

CREATE INDEX IF NOT EXISTS password_reset_tokens_used_at_idx
    ON public.password_reset_tokens (used_at);

COMMIT;
