BEGIN;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending_verification';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_status_check'
          AND conrelid = 'public.users'::regclass
    ) THEN
        ALTER TABLE public.users
            ADD CONSTRAINT users_status_check
            CHECK (status IN ('pending_verification', 'active', 'suspended', 'disabled'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    last_sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT email_verification_tokens_token_hash_unique UNIQUE (token_hash),
    CONSTRAINT email_verification_tokens_expires_after_created CHECK (expires_at > created_at),
    CONSTRAINT email_verification_tokens_used_after_created CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX IF NOT EXISTS email_verification_tokens_user_id_idx
    ON public.email_verification_tokens (user_id);

CREATE INDEX IF NOT EXISTS email_verification_tokens_expires_at_idx
    ON public.email_verification_tokens (expires_at);

CREATE INDEX IF NOT EXISTS email_verification_tokens_used_at_idx
    ON public.email_verification_tokens (used_at);

CREATE INDEX IF NOT EXISTS email_verification_tokens_last_sent_at_idx
    ON public.email_verification_tokens (last_sent_at);

COMMIT;
